
---
title: "Research"
permalink: /research/
---

## Peer-Reviewed Publications

Joyce, Conner. "Do states constrain non-state hackers? International Telecommunication Union elections and non-state cyber aggression." OnlineFirst at the *Journal of Conflict Resolution*. [(Article)](https://journals.sagepub.com/doi/10.1177/00220027251323557){target=_blank} [(Replication)](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SETYU7){target=_blank}


## Under Review or Submitted

Joyce, Conner. "Political action in the dark web: Political mobilization and radicalization in illicit digital networks." [(Manuscript)](https://osf.io/preprints/socarxiv/x6yh4_v1){target=_blank}

- *Franklin L. Burdette/Pi Sigma Alpha APSA Best Overall Paper Award 2026*
- *Robert M. Howard SPSA Best Paper Award 2025*
- *Malcolm Jewell Award SPSA Best Graduate Student Paper Award 2025*

Joyce, Conner, Maranda Joyce, Agustin Prinetti. “Bystanders on social media: Audience moderation and the spread of online extremism.” [(Manuscript)](https://drive.google.com/file/d/1t0uDJFp0w5Gp1YFr1LUt71CCfKYVIDcN/view){target=_blank}


## Working Papers

Huff, Connor, Conner Joyce, Caleb Lucas. "AI-enabled terrorism and public attitudes about responsibility." [(Manuscript)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6183059){target=_blank}

Joyce, Conner.  "Are cyber-attacks the tools of hawks or doves? Cyber retaliation and US public opinion."

Johnson, Jesse, Conner Joyce, Ashley Leeds, and Scott Wolford.  "Intervention and separate peace in civil war." 

## Works in Progress

Conner Joyce. “How moralization mobilizes hacktivist communities during conflicts." 

Henn, Soeren, Connor Huff, Conner Joyce, Emily Myers, and Kaitlyn Robinson. "Wartime experiences and post-war political participation."

Huff, Connor, Conner Joyce, Caleb Lucas. “How the public responds to AI-enabled terrorism.”
